DB = 'monica.db'
FROM = "From"
MSG = "Body"
SPOOKY_INDEX = 4
US = "+16508351609"
BEAKS = "+16464630213"
HOST_NAME = ""
USER_PORT_NUMBER = 80
TWILIO_SIGNATURE = "x-twilio-signature"
CMD = "command"
USER = "user"
RSP = "response"
SWITCH_ID = "switch"
SWITCH_NAME = "name"
SWITCH_STATUS = "status"
FOLLOW_TIME = "kunle"
VALID_CMDS = ["follow", "unfollow", "add", "remove", "status", "list", "setname", "setdefault"]
ARGS = "arguments"
DEFAULT_ERROR_MESSAGE = "Sorry, there was an error in your command."
FOLLOW_MSGS = ["You are now following switch ", "You are already following switch ", "You must add a switch to your switch list before following"]
UNFOLLOW_MSGS = ["You are not following switch ", "You are no longer following switch "]
ADD_MSGS = ["You have added the following switch to your switch list: "]
REMOVE_MSGS = ["You must first add a switch to your switch list before removing it", "You have removed the following switch from your switch list: "]
STATUS_MSGS = ["Your device is currently ", "You must first follow a switch before using the status command"]
LIST_MSGS = ["Your switch list is: "]
SETNAME_MSGS = []
SETDEF_MSGS = []
